# Copyright (c) 2025 Anonymous
# SPDX-License-Identifier: MIT

from typing import override

from code_agent.tools.base import Tool, ToolCallArguments, ToolExecResult, ToolParameter


class PlanSubagentTool(Tool):
    """Generate the pseudo plans including the natural language functionality descriptions and potential function references for the intended code synthesis task."""

    def __init__(self, model_provider: str | None = None) -> None:
        super().__init__(model_provider)

    @override
    def get_model_provider(self) -> str | None:
        return self._model_provider

    @override
    def get_name(self) -> str:
        return "plan_subagent"

    @override
    def get_description(self) -> str:
        return "Generate the pseudo plans including the natural language functionality descriptions and potential function references for the intended code synthesis task."

    @override
    def get_parameters(self) -> list[ToolParameter]:
        return [
            ToolParameter(
                name="number",
                type="int",
                description="The number of plans that requires to be generated by the planning agent.",
                required=True,
            ),
        ]

    @override
    async def execute(self, arguments: ToolCallArguments) -> ToolExecResult:
        number = str(arguments["number"]) if "number" in arguments else None
        if number is None:
            return ToolExecResult(
                error=f"No or wrong number provided for the {self.get_name()} tool",
                error_code=-1,
            )
            # return ToolExecResult(output="Task done.")

        else:
            # return ToolResult(
            #     name=tool_call.name,
            #     success=tool_exec_result.error_code == 0,
            #     result=tool_exec_result.output,
            #     error=tool_exec_result.error,
            #     call_id=tool_call.call_id,
            #     id=tool_call.id,
            # )
            return ToolExecResult(output="Task done.")
